name: lint-pr-title
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  check_commit_conventions:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check commit conventions
        uses: wagoid/commitlint-github-action@v2
        with:
          configFile: .commitlintrc.yml
          failOnWarnings: true